### ISSUE TITLE
atscm import sometimes has errors

### ISSUE THREAD

**Issue by IngMichaelMayr** [atSCM/atscm#252] opened 2019-02-05 14:01 UTC
*Insert error description here*

![image](https://user-images.githubusercontent.com/34569639/52278200-c32ddd80-2956-11e9-87cc-ecf448d7cc2f.png)

**Steps to reproduce error**

 - atscm import on a newly created, empty nodes.db

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | Windows 10 |
| atscm         |         >=1.0.0-beta.18 | 
| atscm-cli     |     0.7.0 | 
| atvise server | 2.5.9 & 3.2.0 |
| node          |          9.3.0 | 
| npm           |           5.6.0 | 
 
</details>

**Comment by LukasHechenberger** [comment] 2019-02-26 12:23
In fact, currently every **first** `atscm import` fails.
It seems to be caused by weird server behaviour: Importing the scripts returns a good status before the folder `SYSTEM.LIBRARY.ATVISE.SERVERSCRIPTS.atscm` is actually created. Therefore creating and writing the node `SYSTEM.LIBRARY.ATVISE.SERVERSCRIPTS.atscm.version` fails (currently without printing an error). On the second (and every following) attempt the folder exists and the import task works as expected.

We'll have to:
 - Check status after writing the version node
   - On bad status retry writing the version node after some delay (maybe 200ms)

@breussm: Could you report this to the atvise server dev team?

**Comment by LukasHechenberger** [comment] 2019-03-06 10:43
Fixed in *1.0.0-beta.23*

**Closed by LukasHechenberger** 2019-03-06 10:43 UTC
